export interface Report {
  id: string;
  location: { latitude: number; longitude: number; geo_hash: string };
  image_url: string;
  total_reaction: number;
  is_reacted: boolean;
  reported_by: { id: string; username: string };
  condition: string;
  category: string;
  category_remark?: string;
  sub_categories?: string[];
  sub_category_remark?: string;
  created_at: number;
  updated_at?: number;
}

export enum ZEBRA_CROSS_BAD_SUB_CATEGORY {
  ZEBRA_CROSS_MISSING = 'ZEBRA_CROSS_MISSING',
  ZEBRA_CROSS_FADED = 'ZEBRA_CROSS_FADED',
  ZEBRA_CROSS_OBSTRUCTED = 'ZEBRA_CROSS_OBSTRUCTED',
  ZEBRA_CROSS_OTHER = 'ZEBRA_CROSS_OTHER',
}

export enum SIDEWALK_BAD_SUB_CATEGORY {
  SIDEWALK_MISSING = 'SIDEWALK_MISSING',
  SIDEWALK_BROKEN = 'SIDEWALK_BROKEN',
  SIDEWALK_DARK = 'SIDEWALK_DARK',
  SIDEWALK_SLIPPERY = 'SIDEWALK_SLIPPERY',
  SIDEWALK_BROKEN_GUIDING_BLOCK = 'SIDEWALK_BROKEN_GUIDING_BLOCK',
  SIDEWALK_MISSING_GUIDING_BLOCK = 'SIDEWALK_MISSING_GUIDING_BLOCK',
  SIDEWALK_OBSTRUCTED_TREE = 'SIDEWALK_OBSTRUCTED_TREE',
  SIDEWALK_OBSTRUCTED_MOTORCYCLE = 'SIDEWALK_OBSTRUCTED_MOTORCYCLE',
  SIDEWALK_OBSTRUCTED_PEDDLERS = 'SIDEWALK_OBSTRUCTED_PEDDLERS',
  SIDEWALK_OTHER = 'SIDEWALK_OTHER',
}

export enum PELICAN_CROSSING_BAD_SUB_CATEGORY {
  PELICAN_CROSSING_MISSING = 'PELICAN_CROSSING_MISSING',
  PELICAN_CROSSING_BROKEN_SOUND = 'PELICAN_CROSSING_BROKEN_SOUND',
  PELICAN_CROSSING_BROKEN_LIGHT = 'PELICAN_CROSSING_BROKEN_LIGHT',
  PELICAN_CROSSING_TOO_FAST = 'PELICAN_CROSSING_TOO_FAST',
  PELICAN_CROSSING_OTHER = 'PELICAN_CROSSING_OTHER',
}

export enum PEDESTRIAN_BRIDGE_BAD_SUB_CATEGORY {
  PEDESTRIAN_BRIDGE_DARK = 'PEDESTRIAN_BRIDGE_DARK',
  PEDESTRIAN_BRIDGE_SLIPPERY = 'PEDESTRIAN_BRIDGE_SLIPPERY',
  PEDESTRIAN_BRIDGE_BROKEN = 'PEDESTRIAN_BRIDGE_BROKEN',
  PEDESTRIAN_BRIDGE_OBSTRUCTED = 'PEDESTRIAN_BRIDGE_OBSTRUCTED',
  PEDESTRIAN_BRIDGE_OTHER = 'PEDESTRIAN_BRIDGE_OTHER',
}

export enum OTHER_BAD_SUB_CATEGORY {
  OTHER_MISSING = 'OTHER_MISSING',
  OTHER_BROKEN = 'OTHER_BROKEN',
  OTHER_OTHER = 'OTHER_OTHER',
}

export enum ZEBRA_CROSS_GOOD_SUB_CATEGORY {
  ZEBRA_CROSS_NO_VEHICLE = 'ZEBRA_CROSS_NO_VEHICLE',
  ZEBRA_CROSS_CLEAN = 'ZEBRA_CROSS_CLEAN',
  ZEBRA_CROSS_OTHER = 'ZEBRA_CROSS_OTHER',
}

export enum SIDEWALK_GOOD_SUB_CATEGORY {
  SIDEWALK_CLEAN = 'SIDEWALK_CLEAN',
  SIDEWALK_NO_VEHICLE = 'SIDEWALK_NO_VEHICLE',
  SIDEWALK_NO_PEDDLERS = 'SIDEWALK_NO_PEDDLERS',
  SIDEWALK_BRIGHT = 'SIDEWALK_BRIGHT',
  SIDEWALK_SPACIOUS = 'SIDEWALK_SPACIOUS',
  SIDEWALK_GUIDING_BLOCK_EXISTS = 'SIDEWALK_GUIDING_BLOCK_EXISTS',
  SIDEWALK_GUIDING_BLOCK_CORRECT = 'SIDEWALK_GUIDING_BLOCK_CORRECT',
  SIDEWALK_OTHER = 'SIDEWALK_OTHER',
}

export enum PELICAN_CROSSING_GOOD_SUB_CATEGORY {
  PELICAN_CROSSING_HELPFUL = 'PELICAN_CROSSING_HELPFUL',
  PELICAN_CROSSING_WORKING = 'PELICAN_CROSSING_WORKING',
  PELICAN_CROSSING_GREAT_DURATION = 'PELICAN_CROSSING_GREAT_DURATION',
  PELICAN_CROSSING_OTHER = 'PELICAN_CROSSING_OTHER',
}

export enum PEDESTRIAN_BRIDGE_GOOD_SUB_CATEGORY {
  PEDESTRIAN_BRIDGE_CLEAN = 'PEDESTRIAN_BRIDGE_CLEAN',
  PEDESTRIAN_BRIDGE_BRIGHT = 'PEDESTRIAN_BRIDGE_BRIGHT',
  PEDESTRIAN_BRIDGE_COMFORTABLE = 'PEDESTRIAN_BRIDGE_COMFORTABLE',
  PEDESTRIAN_BRIDGE_SAFE = 'PEDESTRIAN_BRIDGE_SAFE',
  PEDESTRIAN_BRIDGE_OTHER = 'PEDESTRIAN_BRIDGE_OTHER',
}

export enum OTHER_GOOD_SUB_CATEGORY {
  OTHER_TIDY = 'OTHER_TIDY',
  OTHER_CLEAN = 'OTHER_CLEAN',
  OTHER_OTHER = 'OTHER_OTHER',
}

export const REPORT_SUB_CATEGORIES = {
  ZEBRA_CROSS: {
    BAD: Object.values(ZEBRA_CROSS_BAD_SUB_CATEGORY),
    GOOD: Object.values(ZEBRA_CROSS_GOOD_SUB_CATEGORY),
  },
  SIDEWALK: {
    BAD: Object.values(SIDEWALK_BAD_SUB_CATEGORY),
    GOOD: Object.values(SIDEWALK_GOOD_SUB_CATEGORY),
  },
  PELICAN_CROSSING: {
    BAD: Object.values(PELICAN_CROSSING_BAD_SUB_CATEGORY),
    GOOD: Object.values(PELICAN_CROSSING_GOOD_SUB_CATEGORY),
  },
  PEDESTRIAN_BRIDGE: {
    BAD: Object.values(PEDESTRIAN_BRIDGE_BAD_SUB_CATEGORY),
    GOOD: Object.values(PEDESTRIAN_BRIDGE_GOOD_SUB_CATEGORY),
  },
  OTHER: {
    BAD: Object.values(OTHER_BAD_SUB_CATEGORY),
    GOOD: Object.values(OTHER_GOOD_SUB_CATEGORY),
  },
};

// get all values of enum
export const REPORT_SUB_CATEGORY_ENTRIES = [
  ...Object.values(ZEBRA_CROSS_BAD_SUB_CATEGORY),
  ...Object.values(SIDEWALK_BAD_SUB_CATEGORY),
  ...Object.values(PELICAN_CROSSING_BAD_SUB_CATEGORY),
  ...Object.values(PEDESTRIAN_BRIDGE_BAD_SUB_CATEGORY),
  ...Object.values(OTHER_BAD_SUB_CATEGORY),
  ...Object.values(ZEBRA_CROSS_GOOD_SUB_CATEGORY),
  ...Object.values(SIDEWALK_GOOD_SUB_CATEGORY),
  ...Object.values(PELICAN_CROSSING_GOOD_SUB_CATEGORY),
  ...Object.values(PEDESTRIAN_BRIDGE_GOOD_SUB_CATEGORY),
  ...Object.values(OTHER_GOOD_SUB_CATEGORY),
].reduce((acc: string[], val) => {
  acc.push(...Object.values(val));
  return acc;
}, []);
